[phases.setup]
aptPkgs = ['gdal-bin', 'libgdal-dev', 'libgeos-dev']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'cd backend && python manage.py migrate && gunicorn config_app.wsgi --bind 0.0.0.0:$PORT'